spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://localhost:3306/soccer_payments?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082